### ISSUE TITLE
Structural equation models

### ISSUE THREAD

**Issue by zeileis** [cran-task-views/GraphicalModels#3]
The `GraphicalModels` task views should probably say something more generally about structural equation models (SEMs) beyond the `lvnet` package which is currently listed. The [Psychometrics](https://CRAN.R-project.org/view=Psychometrics) task view has a thorough coverage of the topic, because many contributions to SEMs have their origins in psychometrics. Therefore, I would recommend the following for the `GraphicalModels` task view:

* It is not necessary to list everything again.
* Instead, you can link to `r view("Psychometrics")`.
* But you can add a short discussion (possibly just 1 or 2 sentences) that points out packages that are particularly relevant for graphical models as well.

Happy to provide feedback when you have a first draft.

**Comment by zeileis** [comment]
@hojsgaard it would be great if this issue could be addressed to better link between the task views.

**Comment by hojsgaard** [comment]
A reference to Psychometrics has been added.

**Comment by zeileis** [comment]
Perfect, thanks, updated on CRAN now.
